### ISSUE TITLE
'KubeCluster' object has no attribute '_lock'

### ISSUE THREAD

**Issue by rajasgs** [dask/dask-kubernetes#247] opened 2020-05-07 06:09 UTC
I am just testing dask-kubernetes. 

Here is my code
```
from dask_kubernetes import KubeCluster, make_pod_spec
pod_spec = make_pod_spec(image='daskdev/dask:latest',
                              memory_limit='4G', memory_request='4G',
                              cpu_limit=1, cpu_request=1,
                              env={'EXTRA_PIP_PACKAGES': 'fastparquet git+https://github.com/dask/distributed'})

cluster = KubeCluster(pod_spec)
```
When I the the above code on Jupyter lab, I get the error as bleow:

```
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x10e9bec88>>, <Task finished coro=<SpecCluster._correct_state_internal() done, defined at /Users/xyz/anaconda3/envs/py36/lib/python3.6/site-packages/distributed/deploy/spec.py:300> exception=AttributeError("'KubeCluster' object has no attribute '_lock'",)>)
```

Not sure what I am doing here. Some help would be great.

**Comment by jsignell** [comment] 2020-05-08 16:48
Hi @rajasgs, thanks for raising an issue. It'd be helpful to know what versions of dask, distributed, and dask-kubernetes you have installed. I see you are pip installing distributed master in the pod. That might result in a mismatch between the versions of distributed on the worker and in your work environment (where you run `cluster = KubeCluster`)

**Comment by thatcr** [comment] 2020-05-21 10:31
Hello - we see exactly the same problem, with just this code, before we get as far as running any workers/schedulers:

```
from dask_kubernetes import KubeCluster
cluster = KubeCluster.from_yaml("worker-spec.yml")

...

 File ".../lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File ".../lib/python3.7/site-packages/distributed/deploy/spec.py", line 381, in _close
    await self._correct_state()
  File ".../lib/python3.7/site-packages/distributed/deploy/spec.py", line 301, in _correct_state_internal
    async with self._lock:
AttributeError: 'KubeCluster' object has no attribute '_lock'
```

when running on a clean python 3.7 environment from conda-forge, with the requirements file below:

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2020.4.5.1-hecc5488_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-9.2.0-hdf63c60_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sysroot_linux-64-2.12-h3a0023d_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.34-h53a641e_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgomp-9.2.0-h24d8f2e_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-0_gnu.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-9.2.0-h24d8f2e_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.2.1-he1b5a44_1007.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.1-hf484d3e_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1g-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.5-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/yaml-0.2.4-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.2.11-h516909a_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/readline-8.0-hf8c457e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.6.10-hed695b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.30.1-hcee41ef_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-3.7.6-h8356626_5_cpython.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/async-timeout-3.0.1-py_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/attrs-19.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/blinker-1.4-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cachetools-4.1.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/click-7.1.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cloudpickle-1.4.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/dask-core-2.16.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/heapdict-1.0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/idna-2.9-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-0.4.8-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pycparser-2.20-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.7-1_cp37m.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/six-1.14.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sortedcontainers-2.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tblib-1.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/toolz-0.10.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2020.4.5.1-py37hc8dfbb8_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cffi-1.14.0-py37hd463f26_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/chardet-3.0.4-py37hc8dfbb8_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cytoolz-0.10.1-py37h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/msgpack-python-1.0.0-py37h99015e2_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/multidict-4.7.5-py37h8f50634_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/psutil-5.7.0-py37h8f50634_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-modules-0.2.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pysocks-1.7.1-py37hc8dfbb8_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.8.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyyaml-5.3.1-py37h8f50634_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/rsa-4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tornado-6.0.4-py37h8f50634_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/websocket-client-0.57.0-py37hc8dfbb8_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/zict-2.0.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/brotlipy-0.7.0-py37h8f50634_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cryptography-2.9.2-py37hb09aad4_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/setuptools-46.4.0-py37hc8dfbb8_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/yarl-1.3.0-py37h516909a_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/aiohttp-3.6.2-py37h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/distributed-2.16.0-py37hc8dfbb8_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/google-auth-1.14.3-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyjwt-1.7.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyopenssl-19.1.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/oauthlib-3.0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/urllib3-1.25.9-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/kubernetes_asyncio-11.2.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/requests-2.23.0-pyh8c360ce_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/adal-1.2.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/requests-oauthlib-1.2.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-kubernetes-11.0.0-py37hc8dfbb8_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/dask-kubernetes-0.10.1-py_0.tar.bz2
```

**Comment by thatcr** [comment] 2020-05-21 10:42
Hi - we saw the same that was caused by a ~/.kube/config file which was zero-length, giving 'None' as the config dict. A similar problem occurs if it is missing.

It looks like KubeCluster will just carry on regardless with an invalid object if the config fails, so tornodo reports errors afterwards with _lock missing on the partially setup object:

```
 File "/local/data/scratch/thatro/conda/envs/dask-k8s/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 659, in load_config
    with open(path) as f:
TypeError: 'NoneType' object does not support item assignment
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f2a37dccd50>>, <Task finished coro=<SpecCluster._correct_state_internal() done, defined at /local/data/scratch/thatro/conda/envs/dask-k8s/lib/python3.7/site-packages/distributed/deploy/spec.py:300> exception=AttributeError("'KubeCluster' object has no attribute '_lock'")>)
Traceback (most recent call last):
  File "/local/data/scratch/thatro/conda/envs/dask-k8s/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/local/data/scratch/thatro/conda/envs/dask-k8s/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/local/data/scratch/thatro/conda/envs/dask-k8s/lib/python3.7/site-packages/distributed/deploy/spec.py", line 381, in _close
    await self._correct_state()
  File "/local/data/scratch/thatro/conda/envs/dask-k8s/lib/python3.7/site-packages/distributed/deploy/spec.py", line 301, in _correct_state_internal
    async with self._lock:
```

**Comment by jsignell** [comment] 2020-05-21 20:40
Ah thanks for that @thatcr! I guess this issue can just be a case for better error handling in general.

**Comment by MridulS** [comment] 2021-02-09 17:40
Ran into a similar issue and https://github.com/kubernetes-client/python-base/pull/223 just got merged which should take care of the error.

Now this will fail a bit more gracefully :)
``` python
---------------------------------------------------------------------------
ConfigException                           Traceback (most recent call last)
<ipython-input-1-a6aab33ba3f3> in <module>
      6 
----> 7 cluster = KubeCluster(pod_spec)

~/miniconda3/envs/dask/lib/python3.8/site-packages/dask_kubernetes/core.py in __init__(self, pod_template, name, namespace, n_workers, host, port, env, auth, idle_timeout, deploy_mode, interface, protocol, dashboard_address, security, scheduler_service_wait_timeout, scheduler_pod_template, **kwargs)
    412         self.auth = auth
    413         self.kwargs = kwargs
--> 414         super().__init__(**self.kwargs)
    415 
    416     def _get_pod_template(self, pod_template, pod_type):

.....
.....
.....

~/dev/k8s/python/kubernetes/config/kube_config.py in load_config(self, path)
    704 
    705         if config is None:
--> 706             raise ConfigException(
    707                 'Invalid kube-config. '
    708                 '%s file is empty' % path)

ConfigException: Invalid kube-config. /Users/ms/.kube/config file is empty
```

**Comment by jsignell** [comment] 2021-02-12 22:06
Great! Thanks for mentioning that @MridulS

**Comment by jacobtomlinson** [comment] 2021-02-23 15:08
Great thanks! Closing as fixed upstream.

**Closed by jacobtomlinson** 2021-02-23 15:08 UTC
Labels: bug, help wanted
