### ISSUE TITLE
k8s Operator: DaskCluster spec updates do not propagate to pods

### ISSUE THREAD

**Issue by alinazabara** [dask/dask-kubernetes#636] opened 2022-12-16 12:51 UTC
We’ve deployed the disk-operator and custom resources (DaskCluster, DaskAutoscaler) via helm. 

When updating DaskCluster specs (e.g. scheduler container resources requests - cpu and memory) via helm upgrade, DaskCluster custom resource reflects the new configurations correctly; however, the pods (scheduler and workers) are not re-deployed with the new changes.

**Comment by jacobtomlinson** [comment] 2022-12-16 14:10
Thanks for raising this, currently you need to delete/recreate your cluster to make changes.

This is something we would like to add in the future.

**Comment by alinazabara** [comment] 2022-12-16 14:32
@jacobtomlinson got it, thank you for the reply!

**Comment by jacobwhall** [comment] 2023-03-21 00:35
This is also the case with manually scaling the cluster: today I ran a `helm upgrade` with more workers requested and no new workers spun up until I had deleted and recreated the cluster.

**Comment by jacobtomlinson** [comment] 2023-03-21 09:40
@jacobwhall that's correct, you can modify the replicas in the `DaskWorkerGroup`, but changes to the `DaskCluster` are not current propagated to the `DaskWorkerGroup`. Resolving this issue is on our near term roadmap.

**Closed** 2023-05-24 14:07 UTC
Labels: enhancement, operator

**Comment by bnaul** [comment] 2023-05-30 18:41
@jacobtomlinson this might be a separate issue but the behavior described here

> today I ran a helm upgrade with more workers requested and no new workers spun up until I had deleted and recreated the cluster

still seems to be the case if you update the autoscaler params: for example I tried dropping the maximum and nothing seemed to happen to my cluster. does that seem distinct to you and if so should I open a separate issue for propagating autoscaler changes?

**Comment by jacobtomlinson** [comment] 2023-06-05 13:41
@bnaul could you open a new issue for that?

**Comment by bnaul** [comment] 2023-06-05 14:52
@jacobtomlinson I'm no longer able to reproduce, maybe there was a typo or it was just taking a little while to update...? Both of the following are working correctly for me (`alias k=kubectl`)
```
(.venv) ➜  model git:(dask_k8s_operator) ✗ k get daskautoscaler -o yaml brett | yq '.spec'
cluster: brett
maximum: 10
minimum: 0

# Helm upgrade
(.venv) ➜  model git:(dask_k8s_operator) ✗ helm upgrade brett charts/model-services  --reuse-values --set dask.autoscaler.minReplicas=2
Release "brett" has been upgraded. Happy Helming!
NAME: brett
LAST DEPLOYED: Mon Jun  5 10:51:30 2023
NAMESPACE: default
STATUS: deployed
REVISION: 7
TEST SUITE: None
NOTES:
Successfully installed release: model-services.

Your release is named brett.

To learn more about the release, try:

  $ helm status brett
  $ helm get brett
(.venv) ➜  model git:(dask_k8s_operator) ✗ k get daskautoscaler -o yaml brett | yq '.spec'
cluster: brett
maximum: 10
minimum: 2

# 
(.venv) ➜  model git:(dask_k8s_operator) ✗ k patch daskautoscaler brett --type merge --patch '{"spec":{"minimum": 4}}'
daskautoscaler.kubernetes.dask.org/brett patched
(.venv) ➜  model git:(dask_k8s_operator) ✗ k get daskautoscaler -o yaml brett | yq '.spec'
cluster: brett
maximum: 10
minimum: 4
```
