### ISSUE TITLE
dask-kubernetes not setting correct port

### ISSUE THREAD

**Issue by RodrigoNeves95** [dask/dask-kubernetes#195] opened 2019-10-21 11:32 UTC
After updating dask-kubernetes to the latest version when we create a dask cluster and use port as an argument that argument is not being used

```
cluster = KubeCluster.from_dict(worker.spec(), port=32000)
print(cluster.scheduler_address)

'tcp://100.105.93.67:36995'
```

**Comment by jacobtomlinson** [comment] 2019-10-21 13:24
Thanks for raising this! Looks like a regression during the rewrite, sorry about that.

**Comment by jacobtomlinson** [comment] 2019-10-21 16:02
This is now fixed on the master branch and will be out in the next release. In the mean time you can install the master version like this `pip install git+https://github.com/dask/dask-kubernetes.git`.

**Closed** 2019-10-21 16:01 UTC
Labels: bug
