### ISSUE TITLE
SteamClosedError when creating KubeCluster on Kubeflow

### ISSUE THREAD

**Issue by Felihong** [dask/dask-kubernetes#200] opened 2019-10-24 15:40 UTC
Hi there,

I met this StreamClosedError when I created a cluster with 
`cluster = KubeCluster.from_yaml('worker-template.yaml')` on kubeflow jupyter notebook:

```
---------------------------------------------------------------------------
StreamClosedError                         Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py in read(self, deserializers)
    183         try:
--> 184             n_frames = await stream.read_bytes(8)
    185             n_frames = struct.unpack("Q", n_frames)[0]

StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

CommClosedError                           Traceback (most recent call last)
<ipython-input-4-1d49f9431640> in <module>
----> 1 cluster = KubeCluster.from_yaml('worker-template.yaml')

/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py in from_yaml(cls, yaml_path, **kwargs)
    309             d = yaml.safe_load(f)
    310             d = dask.config.expand_environment_variables(d)
--> 311             return cls.from_dict(d, **kwargs)
    312 
    313     @property
```

Assumed that the pod doesn't have enough authorities to create new pods, I created a new role object `jupyter-notebook` and configured new rolebinding as below (the pod using the default ServiceAccount `default-editor`):

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2019-10-16T13:19:58Z"
  name: default-editor
  namespace: kubeflow-hong-zhu
  ownerReferences:
  - apiVersion: kubeflow.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Profile
    name: kubeflow-hong-zhu
    uid: 8022a9fa-f017-11e9-ad0d-42010a840259
  resourceVersion: "4025"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/kubeflow-hong-zhu/rolebindings/default-editor
  uid: a6f95f59-f017-11e9-ad0d-42010a840259
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jupyter-notebook
subjects:
- kind: ServiceAccount
  name: default-editor
  namespace: kubeflow-hong-zhu
```

This however, doesn't solve the problem. Any thoughts?

Thanks :)

**Comment by Felihong** [comment] 2019-10-24 16:04
Sry about the mess here, pressed wrong bottom 😂

**Comment by jacobtomlinson** [comment] 2019-10-25 08:06
Thanks for raising this.

A few questions:
- Did you configure the role according to [the documentation](https://github.com/dask/dask-kubernetes/blob/master/doc/source/index.rst#role-based-access-control-rbac) to allow permissions to create pods?
- Could you share your `'worker-template.yaml'` file?
- Could you share the full error message?
- Could you also share these things as [codeblocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) rather than screenshots, it just helps with troubleshooting.

**Comment by Felihong** [comment] 2019-10-25 11:16
Thank a lot for the info!

So the local cluster can be created without any problems:
![Screenshot 2019-10-25 at 13 13 55](https://user-images.githubusercontent.com/28823328/67566983-54cdbd00-f729-11e9-8ddc-ffb83411d1f8.png)

**Comment by jacobtomlinson** [comment] 2019-10-25 12:55
I'm not sure. I'm trying to reproduce your issue but have been unable so far. Perhaps @jcrist has some thoughts?

**Comment by Felihong** [comment] 2019-10-25 13:13
Btw the Kubeflow cluster is deployed on GCP, not sure if this may help.

**Comment by Kyrremann** [comment] 2019-11-01 08:10
I'm seeing the same behaviour in my on-premise cluster. We're running Kubeflow with Istio, and Dask.

My pod.yml
```
kind: Pod
metadata:
  labels:
    app: dask
spec:
  restartPolicy: Never
  containers:
  - image: customImage
    imagePullPolicy: IfNotPresent
    args: [dask-worker, --nthreads, '2', --no-bokeh, --memory-limit, 6GB, --death-timeout, '60']
    name: dask
```

This code works for me
```
from dask_kubernetes import KubeCluster

cluster = KubeCluster.from_yaml('pod.yaml')
cluster.scale_up(2)
```

but fails when I run
```
import distributed
import dask.array as da

client = distributed.Client(cluster)
```

**Comment by jacobtomlinson** [comment] 2019-11-01 08:50
Ok thanks for the info. 

`cluster.scale_up(2)` should now be `cluster.scale(2)` but I doubt that is related.

**Comment by Kyrremann** [comment] 2019-11-01 09:16
`cluster.scale(2)` didn't change the outcome, but thanks for the update.

I'm pretty sure it's Istio and Envoy who are creating the trouble. I removed Isito sidecar from the Dask pods, but it still fails. Next I'll try to remove the Istio sidecar from the Notebook-server, so that both are outside Istio system.

**Comment by jacobtomlinson** [comment] 2019-11-01 09:32
Hmm curious that it might be an Istio/Envoy problem.

Does setting `deploy_mode='remote'` help? 

https://github.com/dask/dask-kubernetes/blob/master/dask_kubernetes/core.py#L271-L273

**Comment by Kyrremann** [comment] 2019-11-01 09:37
I'll try that, but the reason I'm thinking it's Istio who is stopping me is based on these two:

https://github.com/dask/dask-kubernetes/issues/197
> Currently workers communicate with each other and the scheduler using the standard container network. They are able to discover their own IP and then share that with the scheduler during registration.

And the suggested answer here https://discuss.istio.io/t/question-enable-in-mesh-pod-to-communicate-with-another-in-mesh-pod-using-podip-mtls-enabled/1077

In short, Istio blocks communication over IP, Dask wants to communicate over IP, it fails.

**Comment by jacobtomlinson** [comment] 2019-11-01 09:42
Ah yup that'll be it. My Istio knowledge is a little lacking, how does it expect things to communicate? Always through services?

**Comment by Kyrremann** [comment] 2019-11-01 09:45
Same with my Istio knowledge (just started to learn), but yes, services are the preferred way.

**Comment by Kyrremann** [comment] 2019-11-01 09:47
Remote gave the same error.

Next I'll manually try to make the `serviceentries` with the IP's used, so we know if that at leasts work.

**Comment by jacobtomlinson** [comment] 2019-11-01 09:51
When using the remote scheduler the scheduler is run in a pod and put behind a service (as opposed to running locally). But the workers are still just bare pods. Dask does it's own service discovery where the workers pass their IP addresses to the scheduler when they connect to it (through the service). I guess the problem is the scheduler can't connect back to them at their IP.

Creating a service per worker feels excessive and unnecessary, but maybe that's the way to go here.

**Comment by Kyrremann** [comment] 2019-11-01 10:34
With latest Istio it looks like IP in `serviceentries` won't work.
https://github.com/istio/istio/issues/12341

**Comment by Kyrremann** [comment] 2019-11-01 12:09
Just wanted to confirm that running a notebook without istio, and then starting a Dask cluster (also without Istio) works.

So looks like we/I need to find a way to start using services.

**Comment by jacobtomlinson** [comment] 2019-11-01 12:11
In that case I think we should close this in favour of #197. Thanks for all the testing

**Comment by Kyrremann** [comment] 2019-11-01 12:11
Agree, and I'm happy to help, and continue helping.

**Closed by jacobtomlinson** 2019-11-01 12:11 UTC
Labels: bug

**Comment by Ogaday** [comment] 2020-04-09 11:09
I came across (I think) the same issue. It seems to depend on the version of Istio at least to some extent. On on cluster with `istio 1.2.6` I have the error (trace below), but on a similar cluster with `Istio 1.3.8` and the same resources it works fine!

Relevant versions:
```
Python 3.7
Dask-Kubernetes 0.10.1
Kubernetes (EKS) 1.14.9
```

I created a service account/role/rolebinding exactly as specified in the docs. I am using my own image instead of the daskdev one and it all worked fine on my local microk8s cluster (without Istio enabled).

Code:

```python
with KubeCluster.from_yaml('config/worker-spec.yml') as cluster:
    cluster.adapt(minimum=DASK_MIN_WORKERS, maximum=DASK_MAX_WORKERS)
    with Client(cluster) as client:
        print(client.get_versions(check=True))
```

Error message:

```
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at: tcp://192.168.21.190:40467
distributed.scheduler - INFO -   dashboard at:                     :8787
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/tcp.py", line 240, in write
    stream.write(b)
  File "/usr/local/lib/python3.7/site-packages/tornado/iostream.py", line 546, in write
    self._check_closed()
  File "/usr/local/lib/python3.7/site-packages/tornado/iostream.py", line 1035, in _check_closed
    raise StreamClosedError(real_error=self.error)
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/job.py", line 66, in <module>
    with KubeCluster.from_yaml('config/worker-spec.yml') as cluster:
  File "/usr/local/lib/python3.7/site-packages/dask_kubernetes/core.py", line 640, in from_yaml
    return cls.from_dict(d, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dask_kubernetes/core.py", line 602, in from_dict
    return cls(make_pod_from_dict(pod_spec), **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dask_kubernetes/core.py", line 416, in __init__
    super().__init__(**self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/distributed/deploy/spec.py", line 256, in __init__
    self.sync(self._start)
  File "/usr/local/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 161, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/distributed/utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/distributed/utils.py", line 332, in f
    result[0] = yield future
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/local/lib/python3.7/site-packages/dask_kubernetes/core.py", line 574, in _start
    await super()._start()
  File "/usr/local/lib/python3.7/site-packages/distributed/deploy/spec.py", line 289, in _start
    await super()._start()
  File "/usr/local/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 59, in _start
    await comm.write({"op": "subscribe_worker_status"})
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/tcp.py", line 255, in write
    convert_stream_closed_error(self, e)
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/tcp.py", line 123, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
```

Hope this is useful for the dask-kubernetes contributors (#197) or others with the same issue.

**Comment by alexifm** [comment] 2020-11-25 17:31
Has anyone tried this recently other than @Ogaday?

I did a bit of digging and it seemt that more recent versions of istio have made substantial changes that could allow Dask to work:
https://medium.com/@dinup24/istio-setting-up-ip-address-based-access-control-d16bac59b2d3
