### ISSUE TITLE
Adaptive causes task Recomputation 

### ISSUE THREAD

**Issue by BitTheByte** [dask/dask-kubernetes#436] opened 2022-04-24 22:01 UTC
I really don't know what I'm requesting here but let me explain, the current implementation of Adaptive `dask-kubernetes` relies on ephemeral worker pods, and with how dask's work it may choose to recompute tasks if data is unavailable which happens if a worker died or added this may cause expensive tasks to recompute. what I'm thinking of is central shared storage for data management or maybe something using `StatefulSet`?

I'm not really a Dask expert so apologies if I mixed up something here

**Comment by mrocklin** [comment] 2022-04-24 22:28
Rather than rely on external storage Dask tends to rely on itself, and on very carefully retiring things.

Ideally Dask is gracefully retiring workers.  It stops processing on a worker, moves the data off of that worker to its peers and then finally shuts down the worker.  If this isn't happening then I'd consider it a bug.

**Comment by BitTheByte** [comment] 2022-04-24 22:34
@mrocklin Thanks for replying, I totally agree with you but what i'm experiencing here is a worker pod is killed (exited due to network errors) in such case the data is lost and recomputation happens

**Comment by mrocklin** [comment] 2022-04-24 22:35
I can believe that that is happening.  I would consider it a bug.  Are you able to provide any kind of reproducer?

**Comment by BitTheByte** [comment] 2022-04-24 22:59
@mrocklin  I'm here using only 1 worker to force is behavior every time 

```python
from dask_kubernetes import KubeCluster, make_pod_spec
from dask.distributed import Client


def long_task(task_id):
    from time import sleep
    from requests import get
    URL = "https://webhook.site/3f14e8e8-d39f-4fe6-80e6-16f94381c25b"
    get(f"{URL}?message=HELLO-FROM-TASK-{task_id}")
    sleep(10 * task_id)
    get(f"{URL}?message=GOODBYE-FROM-TASK-{task_id}")
    return task_id


cluster = KubeCluster(make_pod_spec(image='daskdev/dask:latest'))
cluster.adapt(minimum=1, maximum=1)
client = Client(cluster)

f1 = client.submit(long_task, 1)
f2 = client.submit(long_task, f1)

client.gather([f1, f2])
```

What I'm doing is:-

1) Start python script
2) Waiting for `GOODBYE-FROM-TASK-1`
3) Killing worker pod myself

This will result in the recomputation of `Task-1` again, Totally reproducible on +1 workers but more tricky to achieve

**Comment by mrocklin** [comment] 2022-04-24 23:01
Oh, yeah, if you have no other workers then definitely Dask will lose the result.  However adaptive scaling in Dask will also not scale down below a level where you don't have enough workers for storage.

**Comment by BitTheByte** [comment] 2022-04-24 23:04
Yup, I already know this, This is reproducible also when I have 100 active workers, just having one of them die the new spawned one will restart executing tasks finished before because Futures data was kept on the dead worker

**Comment by mrocklin** [comment] 2022-04-24 23:06
Yeah, it would be good to have a reproducer of such a situation.  It *shouldn't* occur, but I wouldn't be surprised to find some bug in the logic. The example given above isn't a reproducer I don't think, because there weren't other workers for the data to migrate to.

**Comment by BitTheByte** [comment] 2022-04-24 23:14
I edited the example, it may be a bit tricky to get it from first time

**Comment by mrocklin** [comment] 2022-04-25 01:44
Yeah, to be clear, if you kill a worker without warning then Dask won't have any chance to send the data to other workers.  That is out of scope for Dask's adaptive behavior.

If you're looking for resilience past that you could consider calling replicate directly to force duplication.   

You might also try Prefect, which has resilient caching mechanisms and has good Dask integration (depending on what you're trying to do).

**Comment by BitTheByte** [comment] 2022-04-25 04:46
Well, I actually noticed this issue cause I used prefect as this causes problems on their side too

https://github.com/PrefectHQ/prefect/issues/5485

**Comment by jacobtomlinson** [comment] 2022-04-25 10:05
I think there are a couple of directions to go here:

- As @mrocklin says workers being killed aggressively will result in recomputation. There isn't much we can do about that.
- From a Kubernetes perspective perhaps we should investigate why workers are being killed this way. You mention pods exiting due to network errors, that sounds like a pretty serious k8s cluster level issue. Pods shouldn't be killed this way regularly. Could you share more information about these errors and what is happening?

**Comment by BitTheByte** [comment] 2022-04-25 13:01
> As @mrocklin says workers being killed aggressively will result in recomputation. There isn't much we can do about that.

I totally agree with that, I tried `client.replicate` but didn't help much (the same behavior applies) maybe can't replicate `Future`
 results to other workers or the new worker doesn't pull the results from the old ones IDK really

> From a Kubernetes perspective perhaps we should investigate why workers are being killed this way. You mention pods exiting due to network errors, that sounds like a pretty serious k8s cluster level issue. Pods shouldn't be killed this way regularly. Could you share more information about these errors and what is happening?

We are doing network heavy operations which could result in a loss of communication on a single node (we run 1 worker/node)
this could take some time between 20s to 30m depending on the load in which case Dask scheduler decides to spawn a new worker - min: 100 max:100 - and thus causes a recomputation on the new worker, once the old one is back online it rejected by the cluster thus exiting the pod

**Comment by BitTheByte** [comment] 2022-04-25 15:41
Internet-scale operations come with its own set of problems 😃

**Comment by jacobtomlinson** [comment] 2022-04-25 15:48
Fair enough, but I'm really not sure how to move forwards here. I don't think a centralised distributed compute engine like Dask can be expected to behave correctly with network outages of that scale.

The only thing I can think is perhaps setting the [distributed.comm.retry](https://docs.dask.org/en/stable/configuration.html#distributed-comm) config options to some very large numbers to keep the scheduler retrying the worker connections for more than 30 mins.

However I would worry that being that forgiving to failures could result in strange behaviour. 

@mrocklin do you have thoughts?

**Comment by BitTheByte** [comment] 2022-04-25 16:12
I really appreciate your help and interest in this issue you guys are really awesome, I tried changing timeouts but it gets really tricky to debug or diagnose failures. I know I'm hitting some technical limits here, I was thinking since we are already using k8s we have the ability to mount shared volumes and somehow force dask to write to disk so once a new pod comes back online it will just load this information from disk to memory. 

Since we don't have any memory constraints, an easier approach is if I managed to replicate the worker state using `client.replicate` or an alternative to the other workers in memory but I couldn't for some reason 


> I'm curious why internet scale would imply blocking the GIL for 30m

It's the Kernel rather than Python itself 😃

**Closed** 2022-06-02 19:45 UTC
Labels: kubecluster
