### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by g2giovanni** [dask/dask-kubernetes#299] opened 2021-02-09 07:58 UTC
**What happened**:

Hi everyone. I'm trying to execute a Prefect flow on Kubernetes with a Dask Executor. I'm getting this error during the run: 

```
Unexpected error: AttributeError("can't set attribute")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/flow_runner.py", line 418, in get_flow_run_state
    with self.check_for_cancellation(), executor.start():
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/prefect/executors/dask.py", line 211, in start
    with self.cluster_class(**self.cluster_kwargs) as cluster:  # type: ignore
  File "C:/Users/giova/Git_Projects/PentaTechnology/earthalytics-engine/dask-flow-new.py", line 48, in <lambda>
  File "/usr/local/lib/python3.8/site-packages/dask_kubernetes/core.py", line 414, in __init__
    super().__init__(**self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/distributed/deploy/spec.py", line 274, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 69, in __init__
    self.name = str(uuid.uuid4())[:8]
AttributeError: can't set attribute
```

I tried with the last Dask distributed version and also with "2020.12.0" but nothing changed. In seem I get `AttributeError: can't set attribute` when setting pod name

**Environment**:

- Dask version: 2020.12.0
- Python version: 3.8
- Operating System: Linuxinside a Docker image)
- Install method (conda, pip, source): pip

**Comment by quasiben** [comment] 2021-02-09 14:08
Hmm, I'm not sure what's going on here.  Can you check that both dask and distributed are updated to latest ?  Additionally, what version of dask-kubernetes are you using ?

**Comment by jrbourbeau** [comment] 2021-02-09 14:42
It looks like there's a conflict with a recent update in `distributed` where `Cluster` objects now have a `name` attribute (xref https://github.com/dask/distributed/pull/4426)

**Comment by quasiben** [comment] 2021-02-09 15:37
But that was resolved in the latest release, correct ?

**Comment by jrbourbeau** [comment] 2021-02-09 17:21
I think the issue is that the base `Cluster` class in distributed is attempting to assign `self.name` here

https://github.com/dask/distributed/blob/7d2a22f94332974825e599dd779b4d98f44dbca2/distributed/deploy/cluster.py#L66-L69

However, `name` is a `property` on `KubeCluster`

https://github.com/dask/dask-kubernetes/blob/d42220bc997576f2c39cac35c8fcef257241c4cd/dask_kubernetes/core.py#L681-L683

which is why we're getting the `AttributeError: can't set attribute` error

**Comment by ryan00** [comment] 2021-02-09 21:23
I can confirm same behavior and analysis. Running into the same issue latest versions.

**Comment by shmulikah** [comment] 2021-02-10 20:32
Experiencing the exact same behaviour.
Environment:
Dask distributed: 2020.12.0
Dask-kuberneted: latest 
OS: MacOS 11.1
Installation method : Pip
Kubernetes version: 1.15.11

**Closed** 2021-02-23 15:07 UTC
Labels: bug
